/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SocksRouteImport } from './routes/socks'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RegularRouteImport } from './routes/regular'
import { Route as InnerwearRouteImport } from './routes/innerwear'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuySkuRouteImport } from './routes/buy.$sku'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SocksRoute = SocksRouteImport.update({
  id: '/socks',
  path: '/socks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularRoute = RegularRouteImport.update({
  id: '/regular',
  path: '/regular',
  getParentRoute: () => rootRouteImport,
} as any)
const InnerwearRoute = InnerwearRouteImport.update({
  id: '/innerwear',
  path: '/innerwear',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySkuRoute = BuySkuRouteImport.update({
  id: '/buy/$sku',
  path: '/buy/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/innerwear': typeof InnerwearRoute
  '/regular': typeof RegularRoute
  '/shipping': typeof ShippingRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/innerwear': typeof InnerwearRoute
  '/regular': typeof RegularRoute
  '/shipping': typeof ShippingRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/innerwear': typeof InnerwearRoute
  '/regular': typeof RegularRoute
  '/shipping': typeof ShippingRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baby'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/innerwear'
    | '/regular'
    | '/shipping'
    | '/socks'
    | '/sports'
    | '/subscriptions'
    | '/buy/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baby'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/innerwear'
    | '/regular'
    | '/shipping'
    | '/socks'
    | '/sports'
    | '/subscriptions'
    | '/buy/$sku'
  id:
    | '__root__'
    | '/'
    | '/baby'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/innerwear'
    | '/regular'
    | '/shipping'
    | '/socks'
    | '/sports'
    | '/subscriptions'
    | '/buy/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BabyRoute: typeof BabyRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  InnerwearRoute: typeof InnerwearRoute
  RegularRoute: typeof RegularRoute
  ShippingRoute: typeof ShippingRoute
  SocksRoute: typeof SocksRoute
  SportsRoute: typeof SportsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  BuySkuRoute: typeof BuySkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socks': {
      id: '/socks'
      path: '/socks'
      fullPath: '/socks'
      preLoaderRoute: typeof SocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular': {
      id: '/regular'
      path: '/regular'
      fullPath: '/regular'
      preLoaderRoute: typeof RegularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innerwear': {
      id: '/innerwear'
      path: '/innerwear'
      fullPath: '/innerwear'
      preLoaderRoute: typeof InnerwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$sku': {
      id: '/buy/$sku'
      path: '/buy/$sku'
      fullPath: '/buy/$sku'
      preLoaderRoute: typeof BuySkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BabyRoute: BabyRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  InnerwearRoute: InnerwearRoute,
  RegularRoute: RegularRoute,
  ShippingRoute: ShippingRoute,
  SocksRoute: SocksRoute,
  SportsRoute: SportsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  BuySkuRoute: BuySkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
