/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SocksRouteImport } from './routes/socks'
import { Route as RegularRouteImport } from './routes/regular'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuySkuRouteImport } from './routes/buy.$sku'

const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SocksRoute = SocksRouteImport.update({
  id: '/socks',
  path: '/socks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularRoute = RegularRouteImport.update({
  id: '/regular',
  path: '/regular',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySkuRoute = BuySkuRouteImport.update({
  id: '/buy/$sku',
  path: '/buy/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/regular': typeof RegularRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/regular': typeof RegularRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/regular': typeof RegularRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/regular' | '/socks' | '/sports' | '/buy/$sku'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/regular' | '/socks' | '/sports' | '/buy/$sku'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/regular'
    | '/socks'
    | '/sports'
    | '/buy/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  RegularRoute: typeof RegularRoute
  SocksRoute: typeof SocksRoute
  SportsRoute: typeof SportsRoute
  BuySkuRoute: typeof BuySkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socks': {
      id: '/socks'
      path: '/socks'
      fullPath: '/socks'
      preLoaderRoute: typeof SocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular': {
      id: '/regular'
      path: '/regular'
      fullPath: '/regular'
      preLoaderRoute: typeof RegularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$sku': {
      id: '/buy/$sku'
      path: '/buy/$sku'
      fullPath: '/buy/$sku'
      preLoaderRoute: typeof BuySkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  RegularRoute: RegularRoute,
  SocksRoute: SocksRoute,
  SportsRoute: SportsRoute,
  BuySkuRoute: BuySkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
