/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomensInnersRouteImport } from './routes/womens-inners'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SocksRouteImport } from './routes/socks'
import { Route as RegularRouteImport } from './routes/regular'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuySkuRouteImport } from './routes/buy.$sku'

const WomensInnersRoute = WomensInnersRouteImport.update({
  id: '/womens-inners',
  path: '/womens-inners',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SocksRoute = SocksRouteImport.update({
  id: '/socks',
  path: '/socks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularRoute = RegularRouteImport.update({
  id: '/regular',
  path: '/regular',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySkuRoute = BuySkuRouteImport.update({
  id: '/buy/$sku',
  path: '/buy/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/regular': typeof RegularRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/womens-inners': typeof WomensInnersRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/regular': typeof RegularRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/womens-inners': typeof WomensInnersRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/regular': typeof RegularRoute
  '/socks': typeof SocksRoute
  '/sports': typeof SportsRoute
  '/womens-inners': typeof WomensInnersRoute
  '/buy/$sku': typeof BuySkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baby'
    | '/regular'
    | '/socks'
    | '/sports'
    | '/womens-inners'
    | '/buy/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baby'
    | '/regular'
    | '/socks'
    | '/sports'
    | '/womens-inners'
    | '/buy/$sku'
  id:
    | '__root__'
    | '/'
    | '/baby'
    | '/regular'
    | '/socks'
    | '/sports'
    | '/womens-inners'
    | '/buy/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BabyRoute: typeof BabyRoute
  RegularRoute: typeof RegularRoute
  SocksRoute: typeof SocksRoute
  SportsRoute: typeof SportsRoute
  WomensInnersRoute: typeof WomensInnersRoute
  BuySkuRoute: typeof BuySkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/womens-inners': {
      id: '/womens-inners'
      path: '/womens-inners'
      fullPath: '/womens-inners'
      preLoaderRoute: typeof WomensInnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socks': {
      id: '/socks'
      path: '/socks'
      fullPath: '/socks'
      preLoaderRoute: typeof SocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular': {
      id: '/regular'
      path: '/regular'
      fullPath: '/regular'
      preLoaderRoute: typeof RegularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$sku': {
      id: '/buy/$sku'
      path: '/buy/$sku'
      fullPath: '/buy/$sku'
      preLoaderRoute: typeof BuySkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BabyRoute: BabyRoute,
  RegularRoute: RegularRoute,
  SocksRoute: SocksRoute,
  SportsRoute: SportsRoute,
  WomensInnersRoute: WomensInnersRoute,
  BuySkuRoute: BuySkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
